### ISSUE TITLE
Keep the transaction submission time in the chain

### ISSUE THREAD

**Issue by richard-julien** [ghost-coin/ghost-legacy#59]
Hi Ghost team,

I'm currently digging into the chain behavior and it looks like than the transaction deposit pool time is not kept in the chain. So after the tx is taken in a block, this information is lost. It could be really cool to keep it. (i'm currently working on an from scratch explorer and this information could be nice to show / analysis)

Im really a beginner in the blockchain but if you confirmed that its a good idea and you have a guide to setup a dev env for the core on windows I could try to help.

Here we can see that the blocktime is used as time for the transaction.
https://github.com/ghost-coin/ghost-core/blob/29d55d70d12a9f5665f7199c02e65f8f99680c7a/src/rpc/rawtransaction.cpp#L150

Time of block available in the definition
https://github.com/ghost-coin/ghost-core/blob/29d55d70d12a9f5665f7199c02e65f8f99680c7a/src/primitives/block.h#L47

Time of transaction submission not available in the definition
https://github.com/ghost-coin/ghost-core/blob/29d55d70d12a9f5665f7199c02e65f8f99680c7a/src/primitives/transaction.h#L84

Thanks !

**Comment by akshaynexus** [comment]
There isnt a real use for this,Best use mempool for that info.
