### ISSUE TITLE
Figure out why some functional tests are being skipped

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [ghost-coin/ghost-legacy#6]
When running functional tests with the command:

```
python3 test/functional/test_runner.py test/functional/*
```

The following tests get skipped. The following is copied from the result.

feature_backwards_compatibility.py               | \u25cb Skipped | 0 s
feature_part_usbdevice.py                        | \u25cb Skipped | 30 s
feature_part_zmq_test.py                         | \u25cb Skipped | 0 s
interface_zmq.py                                 | \u25cb Skipped | 0 s
p2p_dos_header_tree.py                           | \u25cb Skipped | 0 s
wallet_upgradewallet.py                          | \u25cb Skipped | 0 s

We have to fix this. We want all tests to be runnable automatically.

**Comment by oxarbitrage** [comment]
I did some research on this skipped tests. I hope this will help us decide what we want to fix:

- `feature_backwards_compatibility.py` and `wallet_upgradewallet.py` are skipped also in bitcoin current master. I dont think any fix is needed.

- `feature_part_zmq_test.py` and `interface_zmq.py` require `python3-zmq` to be installed, this can be done with:

   `sudo apt-get install python3-zmq`

   This is documented at https://github.com/ghost-coin/ghost-private/tree/master/test#running-tests-locally , once the python module is installed both tests are not skipped and green.

- `feature_part_usbdevice.py` it seems this will need the ghostd to be built with usbdevice(https://github.com/ghost-coin/ghost-private/blob/master/test/functional/feature_part_usbdevice.py#L47). This is coming from particle, test is not present in bitcoin. Need further research.

- `p2p_dos_header_tree.py` skipped intentionally in ghost and in particle(https://github.com/particl/particl-core/blob/master/test/functional/p2p_dos_header_tree.py#L26-L27). This is not skipped in bitcoin however if we dont skip it it will fail. Probably need further research on why is failing and try to enable it.
