### ISSUE TITLE
getaddressdeltas fail to send data

### ISSUE THREAD

**Issue by richard-julien** [ghost-coin/ghost-legacy#60]
Currently executing the command getaddressdeltas with an rpc call fail.

`getaddressdeltas "GLUrg8AqthqABt8U46ZsAZM6DE5217Svfs"`

**Expected behavior**

Expect the transactions deltas for this address.

**Actual behavior**

Response error
`JSON value is not an object as expected`

**To reproduce**

Open the wallet console, try the command.

**System information**
Ghost Core website version or Ghost Core wallet embedded version (0.19.1.6)
Nothing in debug.log

**Comment by akshaynexus** [comment]
You need to execute the command like this
`getaddressdeltas  '{"addresses": ["GLUrg8AqthqABt8U46ZsAZM6DE5217Svfs"]}'`
