### ISSUE TITLE
getaddresstxids start/end option is not taken into account

### ISSUE THREAD

**Issue by richard-julien** [ghost-coin/ghost-legacy#61]
Using getaddresstxids with rpc client to get the transactions doesnt handle the start and stop option.

for example

`getaddresstxids "GYnnU1Bgq9x48KtSfZg7NM7pEtK3KwPovR" 0 10`

**Expected behavior**

No result because this address have no transactions on the first 10 blocks on the chain.

**Actual behavior**

Command return all Tx from 0 to current chain height

**To reproduce**

Open the wallet and write the command or a rpc call.

**System information**

Current ghost core version downloaded from github

**Comment by akshaynexus** [comment]
Use this format to get txes from heights
`getaddresstxids '{"addresses": ["GYnnU1Bgq9x48KtSfZg7NM7pEtK3KwPovR"],"start":1,"end":10}'`
Start needs to be at 1 not 0.
